package com.katyrin.loan_online.utils

const val SPLASH_ACTIVITY_ANIMATION_TIME = 1000L
const val ROTATION_ANIMATED_AMOUNT = 1000f
const val ROTATION_DURATION = 5000L
const val ONE_ITEM = 1
const val QUARTER_SECOND = 250L
const val MINIMUM_PHONE_NUMBER = 11

const val BASE_URL = "http://103.23.208.205:8082/"
const val DB_NAME = "database.db"

const val SHARED_PREFERENCES_LOGIN_DATA = "SHARED_PREFERENCES_LOGIN_DATA"
const val SHARED_PREFERENCES_TOKEN = "SHARED_PREFERENCES_TOKEN"
const val SHARED_PREFERENCES_USERNAME = "SHARED_PREFERENCES_USERNAME"
const val SHARED_PREFERENCES_PASSWORD = "SHARED_PREFERENCES_PASSWORD"
const val LOAN_INFORMATION_NOT_FOUND = "Loan information not found"