package com.katyrin.loan_online.utils

const val ROTATION_ANIMATED_AMOUNT = 750f
const val ROTATION_DURATION = 10000L
const val BASE_URL = "http://103.23.208.205:8082/"
const val ONE_ITEM = 1
const val HALF_SECOND = 500L
const val MINIMUM_PHONE_NUMBER = 11
const val ONE_HUNDRED_TO_DOUBLE = 10.0
const val SHARED_PREFERENCES_LOGIN_DATA = "SHARED_PREFERENCES_LOGIN_DATA"
const val SHARED_PREFERENCES_TOKEN = "SHARED_PREFERENCES_TOKEN"
const val SHARED_PREFERENCES_USERNAME = "SHARED_PREFERENCES_USERNAME"
const val SHARED_PREFERENCES_PASSWORD= "SHARED_PREFERENCES_PASSWORD"