package com.katyrin.loan_online.utils

const val SPLASH_ACTIVITY_ANIMATION_TIME = 1000L
const val ROTATION_ANIMATED_AMOUNT = 1000f
const val ROTATION_DURATION = 5000L
const val ONE_ITEM = 1
const val QUARTER_SECOND = 250L
const val MINIMUM_PHONE_NUMBER = 11
const val FIVE_LETTERS = 5
const val FIRST_CHAR = 0
const val INTERNET_ERROR = 0
const val ERROR_400 = 400
const val ERROR_401 = 401
const val ERROR_403 = 403
const val ERROR_404 = 404
const val DEFAULT_COUNT_LOANS = 1
const val REGISTERED_LOAN = 1
const val FIRST_REVIEWED_LOAN = 1
const val ZERO_REVIEWED_LOAN = 0

const val BASE_URL = "http://103.23.208.205:8082/"
const val DB_NAME = "database.db"

const val SHARED_PREFERENCES_TOKEN = "SHARED_PREFERENCES_TOKEN"
const val SHARED_PREFERENCES_USERNAME = "SHARED_PREFERENCES_USERNAME"
const val SHARED_PREFERENCES_PASSWORD = "SHARED_PREFERENCES_PASSWORD"
const val LOAN_INFORMATION_NOT_FOUND = "Loan information not found"
const val IS_REGISTERED = "IS_REGISTERED"
const val NOTIFY_DATE = "NOTIFY_DATE"
const val NOTIFY_LOANS = "NOTIFY_LOANS"
const val TAG_NOTIFY_WORK = "TAG_NOTIFY_WORK"
const val EXTRA_IS_AUTHORIZED = "EXTRA_IS_AUTHORIZED"

const val LETTER_T = "T"
const val DOT = "."
const val CHAR_FIVE = '5'